"""empty message

Revision ID: 891170b8ffeb
Revises: 96b937a2470d
Create Date: 2024-07-20 13:57:00.551226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891170b8ffeb'
down_revision = '96b937a2470d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
